service: serverless-websocket-example

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  websocketApiRouteSelectionExpression: $request.body.action

plugins:
  - serverless-prune-plugin
  - "@vingle/serverless-tag-plugin"
  - serverless-websockets-plugin

custom:
  prune:
    automatic: true
    number: 5

package:
  artifact: dst.zip

functions:
  websocketHandler:
    handler: handlers.websocket
    events:
      - websocket:
          routeKey: $connect
      - websocket:
          routeKey: $disconnect
      - websocket:
          routeKey: $default

  # connectionHandler:
  #   handler: src/handler.handler
  #   events:
  #     - websocket:
  #         routeKey: $connect
  #     - websocket:
  #         routeKey: $disconnect
  # defaultHandler:
  #   events:
  #     - websocket:
  #         routeKey: $default
  # actionHandler:
  #   events:
  #     - websocket:
  #         routeKey: myAction

# functions:
#   helloAsync:
#     handler: handlers.helloAsync
#     events:
#       - http:
#           path: hello
#           method: get
