service: serverless-websocket-example

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  environment:
    DEBUG: "*"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
    # For send message to client from server
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

  # WebSocket API Setting
  # websocketsApiName: custom-websockets-api-name
  # websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body

plugins:
  - serverless-prune-plugin
  - "@vingle/serverless-tag-plugin"

custom:
  prune:
    automatic: true
    number: 5

package:
  artifact: dst.zip

functions:
  websocket:
    handler: websocket.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

  frontend:
    timeout: 30
    memorySize: 256
    handler: frontend.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

resources:
  Resources:
    DynamoDBSessionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: chat_prod_sessions
        AttributeDefinitions:
          - AttributeName: i
            AttributeType: S
        KeySchema:
          - AttributeName: i
            KeyType: HASH

    # DynamoDBSessionTable:
    #   Type: AWS::DynamoDB::Table
    #   Properties:
    #     BillingMode: PAY_PER_REQUEST
    #     TableName: room_prod_sessions
    #     AttributeDefinitions:
    #       - AttributeName: i
    #         AttributeType: S
    #     KeySchema:
    #       - AttributeName: i
    #         KeyType: HASH
