service: microservice-template

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod

package:
  artifact: dst.zip

functions:
  helloAsync:
    handler: handlers.helloAsync
    events:
      - http:
          path: hello
          method: get
